change configuration

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -28,9 +28,19 @@ jobs:
           HOST: ${{ secrets.HOST }}
           USER: ${{ secrets.USER }}
         run: |
+          echo "Connecting to $HOST"
+          echo "SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY"
+          echo "USER: $USER"
+          
+          # In ra giá trị của HOST
+          echo "Attempting to ping $HOST"
+          ping -c 3 $HOST || echo "Ping failed"
+
           echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
           chmod 600 private_key.pem
+
           # Thêm dòng này để chấp nhận host key
           mkdir -p ~/.ssh
           ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
+
           rsync -r --delete-after ./target/ $USER@$HOST:/path/to/deploy/
