change configuration

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -29,6 +29,8 @@ jobs:
           USER: ${{ secrets.USER }}
         run: |
           echo "Connecting to $HOST"
+          echo "Host value: $HOST"
+          ping -c 3 $HOST || echo "Ping failed"
           echo "SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY"
           echo "USER: $USER"
           
